config/routes.rb
Tracksgiving::Application.routes.draw do
   

  devise_for :users

  match 'developer' => 'static_pages#developer', :as => "developer"
match 'api_basics' => 'static_pages#api_basics', :as => "api_basics"
match 'company_donation' => 'static_pages#company_donation', :as => "company_donation"
match 'customer_donation' => 'static_pages#customer_donation', :as => "customer_donation"
match 'order_cancel' => 'static_pages#order_cancel', :as => "order_cancel"
match 'order_reschedule' => 'static_pages#order_reschedule', :as => "order_reschedule"
match 'show' => 'static_pages#show', :as => "show"

 root :to => "static_pages#index" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
attr_accessible :email, :password, :password_confirmation, :remember_me
 validates :email, :presence =>true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
 end


def developer
end


def api_basics
end

def company_donation
end

def customer_donation
end

def order_cancel
end

def order_reschedule
end

 def show
 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/documentaions_helper.rb
module DocumentaionsHelper
end

app/helpers/documentations_helper.rb
module DocumentationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracksgiving</title>
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <style>
 .sidebar-nav {
        padding: 9px 0;
      }
    </style>
</head>
<body onload="prettyPrint()">
 <div class="navbar navbar-fixed-top">



    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">

           <a class="brand" href="/">Tracksgiving </a>
             <ul class="nav">
                <li class="<%= (controller_name == "static_pages" and action_name == "index") ? "active" : "" %>">
    <a href="/">Home</a>
    </li>
    <li><a href="#">Tracks</a></li>
<li class="divider-vertical"></li>

    <li class="<%= (controller_name == "static_pages" and action_name == "developer" or action_name == "api_basics") ? "active" : "" %>" > <%= link_to "Developer's Corner", developer_path %></li>

<li class="divider-vertical"></li>

<li><a href="#" class ="pull-right"> Link3 </a>  </li>
    <form class="navbar-search pull-left">
    <input type="text" class="search-query" placeholder="Search">
    </form>
    </ul>


<div class="navbar-inner">
<div class="container">
 
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
 
<!-- Be sure to leave the brand out there if you want it shown -->

 
<!-- Everything you want hidden at 940px or less, place within here -->
<div class="nav-collapse">
<ul class="nav">
<li><a href="#" class =".pull-right">Link</a></li>
    <li><a href="#" class ="pull-right">Link</a></li>

</ul>
<!-- .nav, .navbar-search, .navbar-form, etc -->
</div>

 
</div>
</div>


</div>
</div>
</div>
</div>

<% if user_signed_in? -%>
   Signed in as <%= current_user.email %> </t> </br>
<em>Not You? </em>
<%= link_to  'Sign out ', destroy_user_session_path%> 

<% else -%>
<%= link_to 'Sign Up',new_user_registration_path%> or <%= link_to 'sign In', new_user_session_path%>
<% end -%>


<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<div style="padding-left:10px">
     <%= yield %>
</div>
   
            


</body>
</html>

app/views/static_pages/_aspimplementation.html.erb
<span><</span>%Option Explicit%>
<span><</span>!--#include file="./src/helper_functions.inc"-->
<span><</span>!--#include file="./src/order.inc"-->
<span><</span>!--#include file="./src/company_donation.inc"-->
<span><</span>!--#include file="./src/customer_donation.inc"-->
<span><</span>%
	'	Creates a Company donation with the given attributes.
	dim donation1, don1
	Set donation1 = (New CompanyDonation)(22222222030303,"Ordered 2 shawls","2012-05-18","2012-05-21","C","scott.tiger@gmail.com","vHgYNS7dbotHjziuPCZQ","8caf7910-247e-012f-e4a5-442c03154814",2000,1)

	Set don1 = donation1.invoke()

	Response.Write "Success - " & don1.Success & "<span><</span>br>"
	Response.Write don1.status & " :: " & don1.error & " :: <span><</span>b>Tracking url<span><</span>/b> - <span><</span>a href='" & don1.tracking_url & "'>" & don1.tracking_url & "<span><</span>/a>"

	Response.Write "<span><</span>br><span><</span>br>"

	'	Creates a Customer donation with the given attributes.
	dim donation2, don2
	Set donation2 = (New CustomerDonation)(22222222030304, "Ordered 3 shawls", "VISA Transaction #2394092049", "2012-10-20", "2012-10-29","120.302.03.30", "CHWEB","vHgYNS7dbotHjziuPCZQ", "07369b60-4bfd-012f-01f6-1231392834ed", 2000, 2, "Scott Tiger", "scott.tiger92@gmail.com", "UG_P", "AAAAA9999B", "TP_RI","203 Oceanic View", "IN", "MH", "Mumbai", "400001")

	Set don2 = donation2.invoke()

	Response.Write "Success - " & don2.Success & "<span><</span>br>"
	Response.Write don2.status & " :: " & don2.error & " :: <span><</span>b>Tracking url<span><</span>/b> - <span><</span>a href='" & don2.tracking_url & "'>" & don2.tracking_url & "<span><</span>/a>"

	Response.Write "<span><</span>br><span><</span>br>"

	'	Creates an Order instance with the given attributes. Will be used to cancel the 1st donation subsequently.
	Dim order1, ord1
	Set order1 = (new Order)(22222222030304, "vHgYNS7dbotHjziuPCZQ", "customer cancelled order", "2012-05-19")

	Set ord1 = order1.cancel()

	Response.Write "Success - " & ord1.Success & "<span><</span>br>"
	Response.Write ord1.status & " :: " & ord1.error

	Response.Write "<span><</span>br><span><</span>br>"

	'	Creates an Order instance with the given attributes. Will be used to reschedule the 2st donation subsequently.
	Dim order2, ord2
	Set order2 = (new Order)(22222222030303, "vHgYNS7dbotHjziuPCZQ", "Postponed because the boss says so", "2013-01-04")

	Set ord2 = order2.reschedule()

	Response.Write "Success - " & ord2.Success & "<span><</span>br>"
	Response.Write ord2.status & " :: " & ord2.error

%>

app/views/static_pages/_implementation.html.erb
 <h4><a name="asp"></a>Asp Implementation</h4>    </br>   
<pre class="prettyprint linenums pre-scrollable"><code><%= render :partial => "static_pages/aspimplementation" %></code>
</pre>
  <h4><a name="php"></a>Php Implementation</h4>       </br>
<pre class="prettyprint linenums pre-scrollable"><code><%= render :partial => "static_pages/phpimplementation" %></code>
</pre>
  <h4><a name="ruby"></a>Ruby Implementation</h4>      </br> 
<pre class="prettyprint linenums pre-scrollable"><code><%= render :partial => "static_pages/rubyimplementation" %></code>
</pre>
  <h4><a name="java"></a>Java Implementation</h4>      </br> 
<pre class="prettyprint linenums pre-scrollable"><code><%= render :partial => "static_pages/javaimplementation" %></code>
</pre>

app/views/static_pages/_javaimplementation.html.erb
## Customer Donation API (Point of Sale campaign)

Example Usage:

    CustomerDonation custDon = new CustomerDonation();
	custDon.setToken("vHgYNS7dbotHjziuPCZQ");
	custDon.setOrder_id("100200");
	custDon.setOrder_comment("just like that");
	custDon.setOrder_payment_trx_details("VISA trx #2394092049");
	custDon.setOrder_submission_date(new GregorianCalendar(2012, 02, 04));
	custDon.setOrder_due_date(new GregorianCalendar(2012, 02, 15));
	custDon.setOrder_ipaddress("129.203.20.20");
	custDon.setOrder_channel_code("CHWEB");
	custDon.setCampaign_key("8c98a1d0-247e-012f-e4a3-442c03154814");
	custDon.setDonation_amount(115.0f);
	custDon.setProject_id(2);
	custDon.setDonor_name("Stewie Griffin");
	custDon.setDonor_email("stewie.grifin@familyguy.com");
	custDon.setDonor_genre("UG_P");
	custDon.setDonor_pan_number("");
	custDon.setDonor_tax_payer("TP_RI");
	custDon.setDonor_addressline("quohog");
	custDon.setDonor_country_iso2("IN");
	custDon.setDonor_state_iso2("MH");
	custDon.setDonor_city("Pune");
	custDon.setDonor_zipcode("411028");
	Response response = custDon.invoke();

## Company Donation API (Event triggered campaign)

Example Usage:

    CompanyDonation compDon = new CompanyDonation();
	compDon.setToken("vHgYNS7dbotHjziuPCZQ");
	compDon.setOrder_id("102003");
	compDon.setOrder_comment("company donation for abc Funds");
	compDon.setOrder_submission_date(new GregorianCalendar(2012, 02, 06));
	compDon.setOrder_due_date(new GregorianCalendar(2012, 02, 07));
	compDon.setOrder_channel_code("CHWEB");
	compDon.setOrder_customer_email("abc@xyz.co.in");
	compDon.setCampaign_key("8caf7910-247e-012f-e4a5-442c03154814");
	compDon.setDonation_amount(101.00);
	compDon.setProject_id(1);
	Response response = compDon.invoke();

## Orders API

* Order Cancellation

Example Usage:

    Order order = new Order();  
    order.setId("10001");  
    order.setToken("vHgYNS7dbotHjziuPCZQ");  
    order.setComment("10000 ko cancel");  
    order.setDue_date(new GregorianCalendar(2012, 02, 28));  
    Response response = order.cancel();  

* Order Rescheduling

Example Usage:

    Order order = new Order();
    order.setId("10001");
    order.setToken("vHgYNS7dbotHjziuPCZQ");
    order.setDue_date(new GregorianCalendar(2012, 02, 28));
    Response response = ord.reschedule();

app/views/static_pages/_menu.html.erb
 
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
               <h3><i class="icon-home"></i><a href="/" style=" color:black"> Home</a></h3>
              <li class="<%= (controller_name == "static_pages" and action_name == "developer") ? "nav-header active" : "nav-header" %>">
<%= link_to "Overview", developer_path %>

</li>
<li class="<%= (controller_name == "static_pages" and action_name == "api_basics") ? "nav-header active" : "nav-header" %>">
<%= link_to "Basics", api_basics_path %></li>


              <li class=""><h4>Basics</h4></li>
              <li><a href="#">How we help improve donations</a></li>
              <li><a href="#">How It Works</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Types</li>
              <li class="<%= (controller_name == "static_pages" and action_name == "company_donation") ? "nav-header active" : "nav-header" %>"><%= link_to "Company donation", company_donation_path %></li>
              <li class="<%= (controller_name == "static_pages" and action_name == "customer_donation") ? "nav-header active" : "nav-header" %>"><%= link_to "Customer Donation", customer_donation_path %></li>
              <li class="<%= (controller_name == "static_pages" and action_name == "order_cancel") ? "nav-header active" : "nav-header" %>"><%= link_to "Order Cancellation", order_cancel_path %></li>
              <li class="<%= (controller_name == "static_pages" and action_name == "order_reschedule") ? "nav-header active" : "nav-header" %>"><%= link_to "Order Rescheduling", order_reschedule_path %></li>
              
                 <li class="nav-header">Implementations</li>
               <ul>
                <li>    <a href="#asp">ASP</a></li>
                    <li><a href="#php">PHP</a></li>
                    <li><a href="#ruby">RUBY</a></li>
                   <li> <a href="#java">JAVA</a></li>
                    
     
    </ul>
          </div>

app/views/static_pages/_phpimplementation.html.erb
<span><</span>?php

   require("./src/company_donation.php");
   require("./src/customer_donation.php");
   require("./src/order.php");
   
   //Creates a Company donation with the given attributes.
   $donation1 = new CompanyDonation(345,"Ordered 2 shawls","2012-03-07","2012-03-15","C","scott.tiger@gmail.com","vHgYNS7dbotHjziuPCZQ","8caf7910-247e-012f-e4a5-442c03154814",11981,1);
   $don1 = $donation1->invoke();
   echo $don1->status . " :: ".$don1->error." :: <span><</span>b>Tracking url<span><</span>/b> - ".$don1->tracking_url;
	   
   echo "<span><</span>br>";
   
   //Creates a Customer donation with the given attributes.
   $donation2 = new CustomerDonation(56, "Ordered 3 shawls", "VISA Transaction #2394092049", "2012-10-20", "2012-10-29","120.302.03.30", "CHWEB","vHgYNS7dbotHjziuPCZQ", "8c98a1d0-247e-012f-e4a3-442c03154814", 301.9, 2,"Scott Tiger", "scott.tiger92@gmail.com", "UG_P", "AAAAA9999B", "TP_RI","203 Oceanic View", "IN", "MH", "Mumbai", "400001");
   $don2 = $donation2->invoke();
   echo $don2->status . " :: ".$don2->error." :: <span><</span>b>Tracking url<span><</span>/b> - ".$don2->tracking_url;
   
   echo "<span><</span>br>";
   
   //Creates an Order instance with the given attributes. Will be used to cancel the 1st donation subsequently.
   $order1 = new Order(345, "vHgYNS7dbotHjziuPCZQ", "cancellation comment", "2012-03-10");
   $ord1 = $order1->cancel();
   echo $ord1->status . " :: ".$ord1->error;
   
   echo "<span><</span>br>";
   
   //Creates an Order instance with the given attributes. Will be used to reschedule the 2st donation subsequently.
   $order2 = new Order(56, "vHgYNS7dbotHjziuPCZQ", "cancellation comment", "2012-11-10");
   $ord2 = $order2->reschedule();
   echo $ord2->status . " :: ".$ord2->error;
   
?>

app/views/static_pages/api_basics.html.erb
<div class="container-fluid">
     <div class="row-fluid">
          <div class="row">
               <div class="span2">
                   <%= render :partial => "static_pages/menu" %>
               </div>
               <div class="span10">
               <h2>Basics</h2>
               </div>
          </div>
     </div>
</div>

app/views/static_pages/developer.html.erb
<div class="container-fluid">
     <div class="row-fluid">
<div class="row">
<div class="span2">
<%= render :partial => "static_pages/menu" %>
</div>
<div class="span10">
<h2> Developer APIs</h2>
 <p>The TracksGiving API allows you to integrate your front-end systems directly into TracksGiving, so you can completely control your customers’ experience and pass data back and forth to us behind the scenes.</p>
</div>
</div>
</div>
</div>    

app/views/static_pages/documentation.html.erb
<%= render :partial => "static_pages/menu" %>
<div class= "span10">
                <p>TracksGiving is a "back-end" platform to transparently manage any initiative that has charitable giving as part of its goal. </p>
       <a href="https://secure.tracksgiving.com/tour"> Take a tour </a>
                  
              <div class="tabbable">
    <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Ruby</a></li>
    <li><a href="#tab2" data-toggle="tab">PHP</a></li>
    <li><a href="#tab3" data-toggle="tab">ASP</a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    <p>I'm in Section 1.</p>
    </div>
    <div class="tab-pane" id="tab2">
    <p>Howdy, I'm in Section 2.</p>
      <div class="tab-pane" id="tab3">
    <p>Howdy, I'm in Section 3.</p>
     </div>
    </div>
    </div>


</div> 

app/views/static_pages/index.html.erb
<h1> Welcome to Home Page </h1>

app/views/static_pages/order_cancel.html.erb
<div class="container-fluid">
     <div class="row-fluid">
          <div class="row">
               <div class="span2">
                   <%= render :partial => "static_pages/menu" %>
               </div>
             <div class="span9">
               <h2>Order cancellations</h2>              


<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>
<div class="tabbable">
    <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Ruby</a></li>
    <li><a href="#tab2" data-toggle="tab">PHP</a></li>
    <li><a href="#tab3" data-toggle="tab">ASP</a></li>
     <li><a href="#tab3" data-toggle="tab">JAVA</a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    <p>I'm in Section 1.</p>
    <pre class="prettyprint
    linenums">
    &lt;p&gt;Sample text here...&lt;/p&gt;
    </pre>
    </div>
    <div class="tab-pane" id="tab2">
    <p>Howdy, I'm in Section 2.</p>
    <pre class="prettyprint linenums pre-scrollable">
<li>&lt;p&gt;Sample text here...&lt;/p&gt;</li>
<li>&lt;p&gt;Sample text here..&lt;/p&gt;</li>
</pre>
     </div>
      <div class="tab-pane" id="tab3">
    <p>Howdy, I'm in Section 3.</p>

 <pre class="prettyprint linenums pre-scrollable">
<code>
<span><</span><span>%=</span>

Class Order
		'	Private Attributes
		Dim order_id, token, comment, due_date
		
		'	Methods of the class Order.
		Public Default Function Init(id, token, comment, due_date)
			Me.order_id = id
			Me.token = token
			Me.comment = comment
			Me.due_date = due_date
			Set Init = Me
		End Function
		
		Public Function Validate()
			If IsEmpty(order_id) OR IsEmpty(token) OR IsEmpty(comment) OR IsEmpty(due_date) Then
				Validate = False
			Else
				Validate = True
			End If
		End Function
		
		Public Function Validate_Message()
			Dim error_mess
			
			error_mess = "The errors are - "
			if IsEmpty(order_id) then 
				error_mess = error_mess & " order_id not set;"
			End If
			if IsEmpty(token) then
				error_mess = error_mess & " token not set;"
			End If
			if IsEmpty(comment) then
				error_mess = error_mess & " comment not set;"
			End If
			if IsEmpty(due_date) then
				error_mess = error_mess & " due_date not set;" 
			End If
			
			Set Validate_Message = (New APIResponse)(400, error_mess, "", "", "")
		End Function
		
		Public Function cancel()
			Dim base_url, response_xml, url

		 	base_url= "https://secure.tracksgiving.com"
			If Validate() Then
				url = base_url & "/api/v1/orders/" & order_id & ".xml"

				response_xml = api_caller(url,"_method=DELETE&token=" & token & "&comment=" & comment, "POST", "xml")
				Set cancel = extract_from_xml(response_xml)
			Else
				Set cancel = Validate_Message()
			End If
		End Function
		
		Public Function reschedule()
			If Validate() then
				Dim base_url, response_xml, url

				base_url = "https://secure.tracksgiving.com"
				url = base_url & "/api/v1/orders/" & order_id & ".xml"
				
				response_xml = api_caller(url,"_method=PUT&token=" & token & "&due_date=" & due_date, "POST", "xml")
				Set reschedule = extract_from_xml(response_xml)
			Else 
				Set reschedule = Validate_Message()
			End If
		End Function
	End Class
%>




</code>
</pre>

     </div>
     <div class="tab-pane" id="tab4">
    <p>Howdy, I'm in Section 4.</p>
         </div>
    </div>
    

 </div>
<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>
         
         <h3>Implementations</h3>
</br>
 <%= render :partial => "static_pages/implementation" %> 
          </div>
     </div>
</div>

app/views/static_pages/order_reschedule.html.erb
<div class="container-fluid">
     <div class="row-fluid">
          <div class="row">
               <div class="span2">
                   <%= render :partial => "static_pages/menu" %>
               </div>
               <div class="span9">
               <h2>Order Rescheduling</h2>              


<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>
<div class="tabbable">
    <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Ruby</a></li>
    <li><a href="#tab2" data-toggle="tab">PHP</a></li>
    <li><a href="#tab3" data-toggle="tab">ASP</a></li>
     <li><a href="#tab3" data-toggle="tab">JAVA</a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    <p>I'm in Section 1.</p>
    <pre class="prettyprint
    linenums">
    &lt;p&gt;Sample text here...&lt;/p&gt;
    </pre>
    </div>
    <div class="tab-pane" id="tab2">
    <p>Howdy, I'm in Section 2.</p>
    <pre class="prettyprint linenums pre-scrollable">
<li>&lt;p&gt;Sample text here...&lt;/p&gt;</li>
<li>&lt;p&gt;Sample text here..&lt;/p&gt;</li>
</pre>
     </div>
      <div class="tab-pane" id="tab3">
    <p>Howdy, I'm in Section 3.</p>
 <pre class="prettyprint linenums pre-scrollable">
<code>
<span><</span><span>%=</span>

Class Order
		'	Private Attributes
		Dim order_id, token, comment, due_date
		
		'	Methods of the class Order.
		Public Default Function Init(id, token, comment, due_date)
			Me.order_id = id
			Me.token = token
			Me.comment = comment
			Me.due_date = due_date
			Set Init = Me
		End Function
		
		Public Function Validate()
			If IsEmpty(order_id) OR IsEmpty(token) OR IsEmpty(comment) OR IsEmpty(due_date) Then
				Validate = False
			Else
				Validate = True
			End If
		End Function
		
		Public Function Validate_Message()
			Dim error_mess
			
			error_mess = "The errors are - "
			if IsEmpty(order_id) then 
				error_mess = error_mess & " order_id not set;"
			End If
			if IsEmpty(token) then
				error_mess = error_mess & " token not set;"
			End If
			if IsEmpty(comment) then
				error_mess = error_mess & " comment not set;"
			End If
			if IsEmpty(due_date) then
				error_mess = error_mess & " due_date not set;" 
			End If
			
			Set Validate_Message = (New APIResponse)(400, error_mess, "", "", "")
		End Function
		
		Public Function cancel()
			Dim base_url, response_xml, url

		 	base_url= "https://secure.tracksgiving.com"
			If Validate() Then
				url = base_url & "/api/v1/orders/" & order_id & ".xml"

				response_xml = api_caller(url,"_method=DELETE&token=" & token & "&comment=" & comment, "POST", "xml")
				Set cancel = extract_from_xml(response_xml)
			Else
				Set cancel = Validate_Message()
			End If
		End Function
		
		Public Function reschedule()
			If Validate() then
				Dim base_url, response_xml, url

				base_url = "https://secure.tracksgiving.com"
				url = base_url & "/api/v1/orders/" & order_id & ".xml"
				
				response_xml = api_caller(url,"_method=PUT&token=" & token & "&due_date=" & due_date, "POST", "xml")
				Set reschedule = extract_from_xml(response_xml)
			Else 
				Set reschedule = Validate_Message()
			End If
		End Function
	End Class
%>




</code>
</pre>



     </div>
     <div class="tab-pane" id="tab4">
    <p>Howdy, I'm in Section 4.</p>
         </div>
    </div>
    

 </div>
<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>

<p>TracksGiving is a young, Mumbai based social enterprise helping businesses cause market. Our first major client is CARE India. They will use TracksGiving to manage their campaigns with corporates.</p>
         <h3>Implementations</h3>
</br>
 <%= render :partial => "static_pages/implementation" %> 
         
          </div>
     </div>
</div>

app/views/static_pages/show.html.erb
<h2> this your profile </h2>
 
<%= User.all %>